from: technologyadvice/node-build:0.12-docker
services:
  - docker:1.8-dind:
      name: docker
      persist: false
tasks:
  env: |
    env
    docker -v
    node -v
  test: npm test
  lint: npm run lint
  build: npm run build